"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type Word={word:string;phonetic:string;zh:string;emoji:string;bubble:string;sentence:string;tone:string;theme:string;score:number};
const rows:(string|number)[][]=[
 ["apple","/ˈæp.əl/","苹果","🍎","Yummy!","An apple is red.","coral","水果乐园",92],["banana","/bəˈnɑː.nə/","香蕉","🍌","Sweet!","I like bananas.","yellow","水果乐园",90],["orange","/ˈɒr.ɪndʒ/","橙子","🍊","Juicy!","The orange is round.","coral","水果乐园",91],["grape","/ɡreɪp/","葡萄","🍇","Pop!","These grapes are purple.","violet","水果乐园",93],
 ["cat","/kæt/","小猫","🐱","Meow!","The cat is cute.","violet","动物朋友",88],["dog","/dɒɡ/","小狗","🐶","Woof!","The dog can run.","yellow","动物朋友",95],["bird","/bɜːd/","小鸟","🐦","Tweet!","A bird can fly.","mint","动物朋友",90],["fish","/fɪʃ/","小鱼","🐟","Splash!","The fish can swim.","mint","动物朋友",92],
 ["red","/red/","红色","🔴","Bright!","My ball is red.","coral","彩虹颜色",94],["blue","/bluː/","蓝色","🔵","Cool!","The sky is blue.","mint","彩虹颜色",91],["green","/ɡriːn/","绿色","🟢","Fresh!","The leaf is green.","mint","彩虹颜色",90],["yellow","/ˈjel.əʊ/","黄色","🟡","Sunny!","The sun is yellow.","yellow","彩虹颜色",93],
 ["mom","/mɒm/","妈妈","👩","Hello!","My mom is kind.","coral","我的家人",94],["dad","/dæd/","爸爸","👨","Hi!","My dad is funny.","mint","我的家人",92],["baby","/ˈbeɪ.bi/","宝宝","👶","Giggle!","The baby is happy.","yellow","我的家人",91],["family","/ˈfæm.əl.i/","家人","👨‍👩‍👧","Together!","I love my family.","violet","我的家人",89],
 ["book","/bʊk/","书","📚","Read!","This is my book.","violet","快乐课堂",93],["pen","/pen/","笔","✏️","Write!","I have a pen.","yellow","快乐课堂",94],["bag","/bæɡ/","书包","🎒","Ready!","My bag is purple.","coral","快乐课堂",91],["school","/skuːl/","学校","🏫","Let’s go!","I go to school.","mint","快乐课堂",90]
];
const bank:Word[]=rows.map(r=>({word:String(r[0]),phonetic:String(r[1]),zh:String(r[2]),emoji:String(r[3]),bubble:String(r[4]),sentence:String(r[5]),tone:String(r[6]),theme:String(r[7]),score:Number(r[8])}));
const recordedWords=new Set(bank.map(w=>w.word));
const storageKey="sprout-adventure-v3";
type Stage="welcome"|"listen"|"speak"|"choose"|"write"|"reward"|"finished";
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function dayNo(s:string){return Math.max(0,Math.floor((new Date(`${s}T12:00:00`).getTime()-new Date("2026-01-01T12:00:00").getTime())/86400000))}

function LetterPad({letter,onDone}:{letter:string;onDone:()=>void}){
 const ref=useRef<HTMLCanvasElement|null>(null),draw=useRef(false),distance=useRef(0),locked=useRef(false),activePointer=useRef<number|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [finishing,setFinishing]=useState(false),[status,setStatus]=useState("沿着浅色字母写一写");
 function context(){return ref.current?.getContext("2d")||null}
 function p(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
 function down(e:React.PointerEvent<HTMLCanvasElement>){if(finishing||locked.current||activePointer.current!==null)return;const c=context() as (CanvasRenderingContext2D&{_last?:{x:number;y:number}})|null;if(!c)return;activePointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);const q=p(e);c.beginPath();c.moveTo(q.x,q.y);c._last=q;c.lineWidth=14;c.lineCap="round";c.lineJoin="round";c.strokeStyle="#6f57d9";draw.current=true;setStatus("正在写…")}
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!draw.current||activePointer.current!==e.pointerId)return;const c=context(),q=p(e);if(c){const prev=(c as CanvasRenderingContext2D&{_last?:{x:number;y:number}})._last;if(prev)distance.current+=Math.hypot(q.x-prev.x,q.y-prev.y);(c as CanvasRenderingContext2D&{_last?:{x:number;y:number}})._last=q;c.lineTo(q.x,q.y);c.stroke()}}
 function up(e:React.PointerEvent<HTMLCanvasElement>){if(!draw.current||finishing||locked.current||activePointer.current!==e.pointerId)return;draw.current=false;activePointer.current=null;const c=context() as (CanvasRenderingContext2D&{_last?:{x:number;y:number}})|null;if(c)c._last=undefined;if(distance.current>90){locked.current=true;setFinishing(true);setStatus("写得真棒！自动进入下一步 ✓");timer.current=setTimeout(onDone,1100)}else setStatus("再描长一点点吧")}
 function cancel(e:React.PointerEvent<HTMLCanvasElement>){if(activePointer.current!==e.pointerId)return;draw.current=false;activePointer.current=null;const c=context() as (CanvasRenderingContext2D&{_last?:{x:number;y:number}})|null;if(c)c._last=undefined;setStatus("没关系，继续沿着字母写")}
 function clear(){if(timer.current)clearTimeout(timer.current);locked.current=false;activePointer.current=null;setFinishing(false);draw.current=false;context()?.clearRect(0,0,ref.current!.width,ref.current!.height);distance.current=0;setStatus("沿着浅色字母写一写")}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 return <div className="letter-practice"><div className={`letter-guide ${finishing?"finishing":""}`}><b>{letter}</b><div className="guide-line top"/><div className="guide-line middle"/><div className="guide-line bottom"/><canvas ref={ref} width="520" height="300" aria-label={`描写字母 ${letter}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel}/></div><div className="letter-actions auto"><button onClick={clear}>{finishing?"↻ 再写一次":"↻ 清除重写"}</button><div className={finishing?"success":""} role="status" aria-live="polite">{status}</div></div></div>
}

export default function Home(){
 const today=iso(new Date());const [date,setDate]=useState(today),[amount,setAmount]=useState(3),[done,setDone]=useState<Record<string,string[]>>({}),[stage,setStage]=useState<Stage>("welcome"),[index,setIndex]=useState(0),[recording,setRecording]=useState(false),[heard,setHeard]=useState(false),[spoken,setSpoken]=useState(false),[wrong,setWrong]=useState(false),[choiceDone,setChoiceDone]=useState(false),[choicePassed,setChoicePassed]=useState(false),[letter,setLetter]=useState(0),[writeRun,setWriteRun]=useState(0),[settings,setSettings]=useState(false),[hydrated,setHydrated]=useState(false),[audioNotice,setAudioNotice]=useState("");const timer=useRef<ReturnType<typeof setTimeout>|null>(null),micStream=useRef<MediaStream|null>(null),micRun=useRef(0),wordAudio=useRef<HTMLAudioElement|null>(null),englishVoice=useRef<SpeechSynthesisVoice|null>(null),playbackRun=useRef(0),audioStartTimer=useRef<ReturnType<typeof setTimeout>|null>(null),speechStartTimer=useRef<ReturnType<typeof setTimeout>|null>(null),speechResumeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 // Client storage is intentionally restored after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(storageKey)||"{}");setDone(s.done||{});setAmount(s.amount||3)}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(storageKey,JSON.stringify({done,amount}))},[done,amount,hydrated]);
 useEffect(()=>{if(!("speechSynthesis" in window))return;const loadVoices=()=>{const voices=window.speechSynthesis.getVoices();englishVoice.current=voices.find(v=>v.lang.toLowerCase()==="en-us")||voices.find(v=>v.lang.toLowerCase().startsWith("en"))||null};loadVoices();window.speechSynthesis.addEventListener("voiceschanged",loadVoices);return()=>window.speechSynthesis.removeEventListener("voiceschanged",loadVoices)},[]);
 useEffect(()=>()=>{micRun.current+=1;if(timer.current)clearTimeout(timer.current);micStream.current?.getTracks().forEach(track=>track.stop());playbackRun.current+=1;if(audioStartTimer.current)clearTimeout(audioStartTimer.current);if(speechStartTimer.current)clearTimeout(speechStartTimer.current);if(speechResumeTimer.current)clearTimeout(speechResumeTimer.current);const audio=wordAudio.current;if(audio){audio.onplay=null;audio.onended=null;audio.onerror=null;audio.pause();audio.removeAttribute("src");audio.load()}if("speechSynthesis" in window)window.speechSynthesis.cancel()},[]);
 const lesson=useMemo(()=>{const start=(dayNo(date)*amount)%bank.length;return Array.from({length:amount},(_,i)=>bank[(start+i)%bank.length])},[date,amount]);
 const item=lesson[index]||bank[0],completed=done[date]||[];
 const choices=useMemo(()=>{const a=[item,bank[(bank.indexOf(item)+5)%bank.length],bank[(bank.indexOf(item)+11)%bank.length]];const shift=index%3;return [...a.slice(shift),...a.slice(0,shift)]},[item,index]);
 function stopPlayback(){playbackRun.current+=1;if(audioStartTimer.current)clearTimeout(audioStartTimer.current);if(speechStartTimer.current)clearTimeout(speechStartTimer.current);if(speechResumeTimer.current)clearTimeout(speechResumeTimer.current);audioStartTimer.current=null;speechStartTimer.current=null;speechResumeTimer.current=null;const audio=wordAudio.current;if(audio){audio.onplay=null;audio.onended=null;audio.onerror=null;audio.pause();audio.removeAttribute("src");audio.load();wordAudio.current=null}if("speechSynthesis" in window)window.speechSynthesis.cancel();return playbackRun.current}
 function stopRecording(){micRun.current+=1;if(timer.current)clearTimeout(timer.current);timer.current=null;micStream.current?.getTracks().forEach(track=>track.stop());micStream.current=null;setRecording(false)}
 function systemSpeak(text:string,run:number,fromFallback=false){if(run!==playbackRun.current)return;if(!("speechSynthesis" in window)||!("SpeechSynthesisUtterance" in window)){setAudioNotice("当前浏览器未开放声音，请改用 Chrome 并确认网站声音已开启");return}const synth=window.speechSynthesis;synth.cancel();if(synth.paused)synth.resume();const u=new SpeechSynthesisUtterance(text);let started=false;u.lang=englishVoice.current?.lang||"en-US";u.rate=.7;u.pitch=1.08;u.volume=1;if(englishVoice.current)u.voice=englishVoice.current;const clearSpeechTimer=()=>{if(speechStartTimer.current)clearTimeout(speechStartTimer.current);speechStartTimer.current=null};u.onstart=()=>{if(run!==playbackRun.current)return;started=true;clearSpeechTimer();setAudioNotice(fromFallback?"内置音频暂时不可用，已切换为系统英文发音":"")};u.onend=()=>{if(run===playbackRun.current)clearSpeechTimer()};u.onerror=(event)=>{if(run!==playbackRun.current)return;clearSpeechTimer();if(!['canceled','interrupted'].includes(event.error))setAudioNotice("没有播放出声音，请再点一次，并检查平板媒体音量与网站声音权限")};try{synth.speak(u);speechResumeTimer.current=setTimeout(()=>{if(run===playbackRun.current&&synth.paused)synth.resume()},80);speechStartTimer.current=setTimeout(()=>{if(run===playbackRun.current&&!started)setAudioNotice("发音没有启动，请再点一次，并检查浏览器的网站声音权限")},2200)}catch{if(run===playbackRun.current)setAudioNotice("发音没有启动，请再点一次")}}
 function speak(text:string){const run=stopPlayback(),key=text.trim().toLowerCase();if(!recordedWords.has(key)){systemSpeak(text,run);return}const audio=new Audio(new URL(`audio/${key}.wav`,document.baseURI).href);wordAudio.current=audio;audio.preload="auto";audio.volume=1;let usedFallback=false;const clearAudioTimer=()=>{if(audioStartTimer.current)clearTimeout(audioStartTimer.current);audioStartTimer.current=null};const fallback=()=>{if(usedFallback||run!==playbackRun.current)return;usedFallback=true;clearAudioTimer();audio.onplay=null;audio.onended=null;audio.onerror=null;audio.pause();audio.removeAttribute("src");audio.load();if(wordAudio.current===audio)wordAudio.current=null;systemSpeak(text,run,true)};audio.onplay=()=>{if(run!==playbackRun.current)return;clearAudioTimer();setAudioNotice("")};audio.onended=()=>{clearAudioTimer();if(run===playbackRun.current&&wordAudio.current===audio)wordAudio.current=null};audio.onerror=fallback;try{const play=audio.play();audioStartTimer.current=setTimeout(fallback,4000);if(play)play.catch(fallback)}catch{fallback()}}
 function beginListen(){speak(item.word);setHeard(true)}
 async function record(){stopPlayback();stopRecording();const run=micRun.current;setSpoken(false);setRecording(true);let stream:MediaStream|undefined;try{stream=await navigator.mediaDevices?.getUserMedia({audio:true})}catch{}if(run!==micRun.current){stream?.getTracks().forEach(track=>track.stop());return}micStream.current=stream||null;timer.current=setTimeout(()=>{if(run!==micRun.current)return;micStream.current?.getTracks().forEach(track=>track.stop());micStream.current=null;timer.current=null;setRecording(false);setSpoken(true)},2100)}
 function choose(w:Word){if(choiceDone)return;speak(w.word);if(w.word===item.word){setWrong(false);setChoiceDone(true);setChoicePassed(true)}else{setWrong(true);setTimeout(()=>setWrong(false),900)}}
 function nextLetter(){if(letter<item.word.length-1)setLetter(n=>n+1);else setStage("reward")}
 function restartWriting(){stopPlayback();stopRecording();setLetter(0);setWriteRun(n=>n+1);setStage("write")}
 function resetWordSteps(){setHeard(false);setSpoken(false);setChoiceDone(false);setChoicePassed(false);setWrong(false);setLetter(0)}
 function restartWord(){stopPlayback();stopRecording();resetWordSteps();setStage("listen")}
 function collect(){stopPlayback();stopRecording();setDone(x=>({...x,[date]:Array.from(new Set([...(x[date]||[]),item.word]))}));if(index<lesson.length-1){setIndex(n=>n+1);resetWordSteps();setStage("listen")}else setStage("finished")}
 function resetDay(){stopPlayback();stopRecording();setIndex(0);resetWordSteps();setStage("welcome")}
 function changeDate(n:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);setDate(iso(d));resetDay()}
 const stageNumber=stage==="welcome"?0:stage==="listen"?1:stage==="speak"?2:stage==="choose"?3:stage==="write"?4:5;
 return <main className="adventure-shell">
  <header className="adventure-header"><div className="brand"><span className="brand-mark">A</span><span><b>小芽英语</b><small>今日英语冒险</small></span></div><div className="journey-dots" aria-label="本日学习进度">{lesson.map((w,i)=><i key={w.word} className={completed.includes(w.word)?"done":i===index&&stage!=="welcome"?"current":""}>{completed.includes(w.word)?"✓":i+1}</i>)}</div><button className="parent" onClick={()=>setSettings(!settings)}>⚙️ <span>家长中心</span></button></header>
  {settings&&<section className="adventure-settings"><div><b>家长设置</b><small>孩子的主界面只保留当前任务</small></div><span>每日</span>{[3,4,5].map(n=><button key={n} className={amount===n?"selected":""} onClick={()=>{setAmount(n);resetDay()}}>{n}词</button>)}<button onClick={()=>changeDate(-1)}>前一天</button><button onClick={()=>{setDate(today);resetDay()}}>回到今天</button><button className="close" onClick={()=>setSettings(false)}>完成</button></section>}
  <section className="adventure-main">
   <aside className="companion"><img src="/mascot-v2.png" alt="小芽星星陪学角色"/><div className="speech-bubble">{stage==="welcome"?`准备好去${lesson[0]?.theme}了吗？`:stage==="listen"?"小耳朵准备好，听我读！":stage==="speak"?"现在轮到你开口啦！":stage==="choose"?"听得真认真，找一找吧！":stage==="write"?"一个字母一个字母来！":stage==="reward"?"你完成了一颗单词星！":"今天的冒险完成啦！"}</div></aside>
   <article className={`quest-card stage-${stage}`}>
    {stage!=="welcome"&&stage!=="finished"&&<div className="quest-progress"><span>单词 {index+1}/{lesson.length}</span><div>{[1,2,3,4,5].map(n=><i key={n} className={n<=stageNumber?"on":""}/>)}</div><b>{["","听","说","选","写","奖励"][stageNumber]}</b></div>}
    {stage==="welcome"&&<div className="welcome-stage"><p>DAY {dayNo(date)+1} · {lesson[0]?.theme}</p><h1>今天去哪里探险？</h1><div className="island-card"><span>{lesson.map(w=>w.emoji).join("  ")}</span><b>{lesson[0]?.theme}</b><small>{lesson.length} 颗单词星等你收集</small></div><button className="adventure-primary" onClick={()=>setStage("listen")}>开始今天的冒险 <b>→</b></button></div>}
    {stage==="listen"&&<div className="single-stage"><p className="stage-label">第一关 · 听一听</p><button className={`hero-object sound-picture ${item.tone}`} onClick={beginListen} aria-label={`播放 ${item.word} 的读音`}><span>{item.emoji}</span><i>{item.bubble}</i><em>🔊 点击图片听读音</em></button><h1>{item.word}</h1><p className="word-meta">{item.zh} · {item.phonetic}</p><div className="stage-actions"><button className="soft-repeat" onClick={beginListen}>{heard?"↻ 再听一次":"🔊 听小芽读"}</button>{heard&&<button className="adventure-primary compact" onClick={()=>{setSpoken(false);setStage("speak")}}>我听好了，去说一说 →</button>}</div></div>}
    {stage==="speak"&&<div className="single-stage"><p className="stage-label">第二关 · 勇敢说</p><button className={`hero-object sound-picture small ${item.tone}`} onClick={()=>speak(item.word)} aria-label={`播放 ${item.word} 的读音`} disabled={recording}><span>{item.emoji}</span><em>🔊 点击听读音</em></button><h1>{item.word}</h1><button className={`big-mic ${recording?"recording":""} ${spoken?"complete":""}`} onClick={record} disabled={recording}>{spoken?"✓":"🎙️"}</button><h2>{recording?"小芽正在认真听…":spoken?"听到了，读得真勇敢！":"大声读出来吧！"}</h2><small>{recording?"说完后可以选择再读一次":spoken?"想多练几次也可以":"点击麦克风开始"}</small>{spoken&&<div className="stage-actions"><button className="soft-repeat" onClick={record}>↻ 再读一次</button><button className="adventure-primary compact" onClick={()=>{setChoiceDone(false);setChoicePassed(false);setStage("choose")}}>去找图片 →</button></div>}</div>}
    {stage==="choose"&&<div className="single-stage"><p className="stage-label">第三关 · 找一找</p><h2>哪一个是 <strong>{item.word}</strong>？</h2><button className="tiny-listen" onClick={()=>speak(item.word)}>🔊 再听一次</button><div className={`choice-grid ${wrong?"shake":""}`}>{choices.map(w=><button key={w.word} className={choiceDone&&w.word===item.word?"correct":""} onClick={()=>choose(w)} disabled={choiceDone} aria-label={`${w.zh}，点击播放 ${w.word} 并选择`}><span>{w.emoji}</span><b>{w.zh}</b><em>🔊</em></button>)}</div>{wrong&&<p className="gentle-tip">差一点点，再听听看 💛</p>}{choiceDone&&<p className="success-tip">找对啦！{item.word} 就是 {item.zh} ✓</p>}{choicePassed&&!choiceDone&&<p className="success-tip">可以重新选择，想继续时也能去写字母</p>}{choicePassed&&<div className="stage-actions"><button className="soft-repeat" onClick={()=>{setChoiceDone(false);setWrong(false);speak(item.word)}}>↻ 再选一次</button><button className="adventure-primary compact" onClick={()=>{setLetter(0);setStage("write")}}>去写字母 →</button></div>}</div>}
    {stage==="write"&&<div className="single-stage write-stage"><p className="stage-label">第四关 · 写一写</p><h2>写第 {letter+1} 个字母</h2><div className="spelling-row">{item.word.split("").map((c,i)=><span key={i} className={i<letter?"done":i===letter?"current":""}>{i<letter?"✓":c}</span>)}</div><LetterPad key={`${index}-${letter}-${writeRun}`} letter={item.word[letter]} onDone={nextLetter}/><button className="soft-repeat write-repeat-all" onClick={restartWriting}>↻ 从头重写本词</button></div>}
    {stage==="reward"&&<div className="reward-stage"><div className="confetti">✦　·　★　·　✦</div><button className="reward-sticker sound-picture" onClick={()=>speak(item.word)} aria-label={`播放 ${item.word} 的读音`}><span>{item.emoji}</span><em>🔊</em></button><p>新贴纸收集成功 · 点击贴纸可再听一次</p><h1>{item.word}</h1><h2>太棒啦，读、找、写都完成了！</h2><div className="reward-stars">⭐ ⭐ ⭐</div><div className="stage-actions reward-actions"><button className="soft-repeat" onClick={restartWriting}>↻ 再写一遍</button><button className="soft-repeat" onClick={restartWord}>↻ 从听开始</button><button className="adventure-primary compact" onClick={collect}>{index<lesson.length-1?"继续探险 →":"完成今天 →"}</button></div></div>}
    {stage==="finished"&&<div className="finished-stage"><span>🏆</span><h1>今日冒险完成！</h1><p>你收集了 {lesson.length} 张单词贴纸，点击可听读音</p><div className="sticker-shelf">{lesson.map(w=><button key={w.word} onClick={()=>speak(w.word)} aria-label={`播放 ${w.word} 的读音`}>{w.emoji}<small>{w.word}　🔊</small></button>)}</div><button className="adventure-primary" onClick={()=>{resetDay();setDate(today)}}>再玩一次</button></div>}
   </article>
  </section>
  {audioNotice&&<div className="audio-notice" role="status" aria-live="polite">🔈 {audioNotice}</div>}
  <footer className="adventure-footer"><span>家长提示</span> 每关只呈现一个任务；单词优先使用内置音频，失败时自动切换系统语音；跟读得分仍为演示反馈。</footer>
 </main>
}
