"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type Word={word:string;phonetic:string;zh:string;emoji:string;bubble:string;sentence:string;tone:string;theme:string;score:number};
const rows:(string|number)[][]=[
 ["apple","/ˈæp.əl/","苹果","🍎","Yummy!","An apple is red.","coral","水果乐园",92],["banana","/bəˈnɑː.nə/","香蕉","🍌","Sweet!","I like bananas.","yellow","水果乐园",90],["orange","/ˈɒr.ɪndʒ/","橙子","🍊","Juicy!","The orange is round.","coral","水果乐园",91],["grape","/ɡreɪp/","葡萄","🍇","Pop!","These grapes are purple.","violet","水果乐园",93],
 ["cat","/kæt/","小猫","🐱","Meow!","The cat is cute.","violet","动物朋友",88],["dog","/dɒɡ/","小狗","🐶","Woof!","The dog can run.","yellow","动物朋友",95],["bird","/bɜːd/","小鸟","🐦","Tweet!","A bird can fly.","mint","动物朋友",90],["fish","/fɪʃ/","小鱼","🐟","Splash!","The fish can swim.","mint","动物朋友",92],
 ["red","/red/","红色","🔴","Bright!","My ball is red.","coral","彩虹颜色",94],["blue","/bluː/","蓝色","🔵","Cool!","The sky is blue.","mint","彩虹颜色",91],["green","/ɡriːn/","绿色","🟢","Fresh!","The leaf is green.","mint","彩虹颜色",90],["yellow","/ˈjel.əʊ/","黄色","🟡","Sunny!","The sun is yellow.","yellow","彩虹颜色",93],
 ["mom","/mɒm/","妈妈","👩","Hello!","My mom is kind.","coral","我的家人",94],["dad","/dæd/","爸爸","👨","Hi!","My dad is funny.","mint","我的家人",92],["baby","/ˈbeɪ.bi/","宝宝","👶","Giggle!","The baby is happy.","yellow","我的家人",91],["family","/ˈfæm.əl.i/","家人","👨‍👩‍👧","Together!","I love my family.","violet","我的家人",89],
 ["book","/bʊk/","书","📚","Read!","This is my book.","violet","快乐课堂",93],["pen","/pen/","笔","✏️","Write!","I have a pen.","yellow","快乐课堂",94],["bag","/bæɡ/","书包","🎒","Ready!","My bag is purple.","coral","快乐课堂",91],["school","/skuːl/","学校","🏫","Let’s go!","I go to school.","mint","快乐课堂",90]
];
const bank:Word[]=rows.map(r=>({word:String(r[0]),phonetic:String(r[1]),zh:String(r[2]),emoji:String(r[3]),bubble:String(r[4]),sentence:String(r[5]),tone:String(r[6]),theme:String(r[7]),score:Number(r[8])}));
const storageKey="sprout-adventure-v3";
type Stage="welcome"|"listen"|"speak"|"choose"|"write"|"reward"|"finished";
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function dayNo(s:string){return Math.max(0,Math.floor((new Date(`${s}T12:00:00`).getTime()-new Date("2026-01-01T12:00:00").getTime())/86400000))}

type Pt=[number,number];
const line=(a:Pt,b:Pt,n=28):Pt[]=>Array.from({length:n+1},(_,i)=>[a[0]+(b[0]-a[0])*i/n,a[1]+(b[1]-a[1])*i/n]);
const quad=(a:Pt,b:Pt,c:Pt,n=34):Pt[]=>Array.from({length:n+1},(_,i)=>{const t=i/n,u=1-t;return[u*u*a[0]+2*u*t*b[0]+t*t*c[0],u*u*a[1]+2*u*t*b[1]+t*t*c[1]]});
const oval=(cx:number,cy:number,rx:number,ry:number,start=-Math.PI/2,end=start+Math.PI*2,n=58):Pt[]=>Array.from({length:n+1},(_,i)=>{const t=start+(end-start)*i/n;return[cx+Math.cos(t)*rx,cy+Math.sin(t)*ry]});
function letterStrokes(ch:string):Pt[][]{switch(ch.toLowerCase()){
 case"a":return[oval(.47,.54,.18,.22),line([.65,.32],[.65,.76])];case"b":return[line([.35,.16],[.35,.77]),quad([.35,.43],[.72,.32],[.68,.58]),quad([.68,.58],[.61,.78],[.35,.73])];case"c":return[oval(.52,.55,.22,.22,-.6,Math.PI*1.55)];case"d":return[oval(.48,.55,.18,.22),line([.66,.16],[.66,.77])];
 case"e":return[line([.67,.55],[.32,.55]),quad([.32,.55],[.37,.28],[.58,.34]),quad([.58,.34],[.78,.49],[.66,.64]),quad([.66,.64],[.5,.82],[.33,.66])];case"f":return[quad([.61,.2],[.39,.1],[.4,.37]),line([.4,.37],[.4,.78]),line([.27,.42],[.6,.42])];case"g":return[oval(.47,.5,.18,.2),line([.65,.31],[.65,.81]),quad([.65,.81],[.52,.93],[.36,.82])];case"h":return[line([.35,.16],[.35,.78]),quad([.35,.48],[.52,.32],[.65,.47]),line([.65,.47],[.65,.78])];
 case"i":return[line([.5,.4],[.5,.78]),oval(.5,.25,.025,.025)];case"k":return[line([.35,.16],[.35,.78]),line([.65,.38],[.35,.57]),line([.45,.51],[.69,.78])];case"l":return[line([.5,.16],[.5,.78])];case"m":return[line([.25,.4],[.25,.78]),quad([.25,.48],[.4,.3],[.5,.48]),line([.5,.48],[.5,.78]),quad([.5,.48],[.66,.3],[.74,.48]),line([.74,.48],[.74,.78])];
 case"n":return[line([.32,.4],[.32,.78]),quad([.32,.49],[.5,.29],[.66,.49]),line([.66,.49],[.66,.78])];case"o":return[oval(.5,.55,.2,.22)];case"p":return[line([.34,.4],[.34,.92]),quad([.34,.45],[.69,.3],[.69,.56]),quad([.69,.56],[.64,.75],[.34,.69])];case"r":return[line([.36,.4],[.36,.78]),quad([.36,.49],[.53,.31],[.67,.43])];
 case"s":return[quad([.68,.38],[.45,.25],[.33,.45]),quad([.33,.45],[.39,.57],[.6,.58]),quad([.6,.58],[.76,.7],[.57,.79]),quad([.57,.79],[.4,.84],[.3,.71])];case"t":return[line([.5,.2],[.5,.7]),line([.33,.42],[.67,.42])];case"u":return[line([.32,.4],[.32,.66]),quad([.32,.66],[.48,.88],[.66,.66]),line([.66,.4],[.66,.78])];case"w":return[line([.23,.4],[.34,.78]),line([.34,.78],[.49,.48]),line([.49,.48],[.64,.78]),line([.64,.78],[.77,.4])];case"y":return[line([.3,.4],[.5,.7]),line([.7,.4],[.5,.7]),line([.5,.7],[.43,.92])];default:return[line([.35,.25],[.65,.75])];}}

function LetterPad({letter,onDone}:{letter:string;onDone:()=>void}){
 const ref=useRef<HTMLCanvasElement|null>(null),demoRef=useRef<HTMLCanvasElement|null>(null),draw=useRef(false),distance=useRef(0),locked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [demoing,setDemoing]=useState(true),[status,setStatus]=useState("看小芽写一遍"),[demoReplay,setDemoReplay]=useState(0);
 function context(){return ref.current?.getContext("2d")||null}
 function p(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
 function down(e:React.PointerEvent<HTMLCanvasElement>){if(demoing||locked.current)return;const c=context() as (CanvasRenderingContext2D&{_last?:Pt})|null;if(!c)return;e.currentTarget.setPointerCapture(e.pointerId);const q=p(e);c.beginPath();c.moveTo(q.x,q.y);c._last=[q.x,q.y];c.lineWidth=14;c.lineCap="round";c.lineJoin="round";c.strokeStyle="#6f57d9";draw.current=true;setStatus("正在写…")}
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!draw.current)return;const c=context(),q=p(e);if(c){const prev=(c as CanvasRenderingContext2D&{_last?:Pt})._last; if(prev)distance.current+=Math.hypot(q.x-prev[0],q.y-prev[1]);(c as CanvasRenderingContext2D&{_last?:Pt})._last=[q.x,q.y];c.lineTo(q.x,q.y);c.stroke()}}
 function up(){if(!draw.current||locked.current)return;draw.current=false;const c=context() as (CanvasRenderingContext2D&{_last?:Pt})|null;if(c)c._last=undefined;if(distance.current>90){locked.current=true;setStatus("写得真棒！自动进入下一步 ✓");setDemoing(true);timer.current=setTimeout(onDone,650)}else setStatus("再描长一点点吧")}
 function cancel(){draw.current=false;const c=context() as (CanvasRenderingContext2D&{_last?:Pt})|null;if(c)c._last=undefined;setStatus("没关系，继续沿着字母写")}
 function clear(){if(timer.current)clearTimeout(timer.current);locked.current=false;draw.current=false;context()?.clearRect(0,0,ref.current!.width,ref.current!.height);distance.current=0;setStatus("轮到你啦，沿着浅色字母写")}
 function replay(){clear();setDemoing(true);setStatus("看小芽写一遍");setDemoReplay(n=>n+1)}
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);locked.current=false;draw.current=false;distance.current=0;context()?.clearRect(0,0,ref.current!.width,ref.current!.height);const canvas=demoRef.current,c=canvas?.getContext("2d"),strokes=letterStrokes(letter);if(!canvas||!c)return;let raf=0,start=0;const reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches,total=strokes.reduce((n,s)=>n+s.length,0),duration=reduceMotion?350:1700;function frame(ts:number){if(!start)start=ts;const progress=Math.min(1,(ts-start)/duration),limit=Math.floor(total*progress);c!.clearRect(0,0,canvas!.width,canvas!.height);c!.lineWidth=11;c!.lineCap="round";c!.lineJoin="round";c!.strokeStyle="#f0b83d";let used=0,last:Pt|null=null;for(const stroke of strokes){if(used>=limit)break;c!.beginPath();for(let i=0;i<stroke.length&&used<limit;i++,used++){const q:Pt=[stroke[i][0]*canvas!.width,stroke[i][1]*canvas!.height];if(i===0)c!.moveTo(q[0],q[1]);else c!.lineTo(q[0],q[1]);last=q}c!.stroke()}strokes.forEach((stroke,i)=>{const q=stroke[0];c!.fillStyle="#ff806f";c!.beginPath();c!.arc(q[0]*canvas!.width,q[1]*canvas!.height,12,0,Math.PI*2);c!.fill();c!.fillStyle="#fff";c!.font="900 12px Arial";c!.textAlign="center";c!.textBaseline="middle";c!.fillText(String(i+1),q[0]*canvas!.width,q[1]*canvas!.height)});if(last){c!.fillStyle="#fff";c!.strokeStyle="#ff806f";c!.lineWidth=5;c!.beginPath();c!.arc(last[0],last[1],9,0,Math.PI*2);c!.fill();c!.stroke()}if(progress<1)raf=requestAnimationFrame(frame);else timer.current=setTimeout(()=>{c!.clearRect(0,0,canvas!.width,canvas!.height);setDemoing(false);setStatus("轮到你啦，沿着浅色字母写")},reduceMotion?80:350)}raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);if(timer.current)clearTimeout(timer.current)}},[letter,demoReplay]);
 return <div className="letter-practice"><div className={`letter-guide ${demoing?"demoing":""}`}><b>{letter}</b><div className="guide-line top"/><div className="guide-line middle"/><div className="guide-line bottom"/><canvas ref={demoRef} className="demo-canvas" width="520" height="300"/><canvas ref={ref} width="520" height="300" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel}/></div><div className="letter-actions auto"><span><button onClick={replay} disabled={demoing}>👀 再看示范</button><button onClick={clear} disabled={demoing}>↻ 重新写</button></span><div className={status.includes("真棒")?"success":""}>{demoing&&<i/>}{status}</div></div></div>
}

export default function Home(){
 const today=iso(new Date());const [date,setDate]=useState(today),[amount,setAmount]=useState(3),[done,setDone]=useState<Record<string,string[]>>({}),[stage,setStage]=useState<Stage>("welcome"),[index,setIndex]=useState(0),[recording,setRecording]=useState(false),[wrong,setWrong]=useState(false),[letter,setLetter]=useState(0),[settings,setSettings]=useState(false),[hydrated,setHydrated]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 // Client storage is intentionally restored after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(storageKey)||"{}");setDone(s.done||{});setAmount(s.amount||3)}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(storageKey,JSON.stringify({done,amount}))},[done,amount,hydrated]);
 const lesson=useMemo(()=>{const start=(dayNo(date)*amount)%bank.length;return Array.from({length:amount},(_,i)=>bank[(start+i)%bank.length])},[date,amount]);
 const item=lesson[index]||bank[0],completed=done[date]||[];
 const choices=useMemo(()=>{const a=[item,bank[(bank.indexOf(item)+5)%bank.length],bank[(bank.indexOf(item)+11)%bank.length]];const shift=index%3;return [...a.slice(shift),...a.slice(0,shift)]},[item,index]);
 function speak(text:string){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.7;u.pitch=1.08;window.speechSynthesis.speak(u)}
 function beginListen(){speak(item.word);setTimeout(()=>setStage("speak"),1150)}
 async function record(){setRecording(true);let stream:MediaStream|undefined;try{stream=await navigator.mediaDevices?.getUserMedia({audio:true})}catch{}timer.current=setTimeout(()=>{stream?.getTracks().forEach(t=>t.stop());setRecording(false);setStage("choose")},2100)}
 function choose(w:Word){if(w.word===item.word){setWrong(false);setStage("write");setLetter(0)}else{setWrong(true);setTimeout(()=>setWrong(false),900)}}
 function nextLetter(){if(letter<item.word.length-1)setLetter(n=>n+1);else setStage("reward")}
 function collect(){setDone(x=>({...x,[date]:Array.from(new Set([...(x[date]||[]),item.word]))}));if(index<lesson.length-1){setIndex(n=>n+1);setStage("listen");setLetter(0)}else setStage("finished")}
 function resetDay(){setIndex(0);setStage("welcome");setLetter(0);setWrong(false)}
 function changeDate(n:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);setDate(iso(d));resetDay()}
 const stageNumber=stage==="welcome"?0:stage==="listen"?1:stage==="speak"?2:stage==="choose"?3:stage==="write"?4:5;
 return <main className="adventure-shell">
  <header className="adventure-header"><div className="brand"><span className="brand-mark">A</span><span><b>小芽英语</b><small>今日英语冒险</small></span></div><div className="journey-dots" aria-label="本日学习进度">{lesson.map((w,i)=><i key={w.word} className={completed.includes(w.word)?"done":i===index&&stage!=="welcome"?"current":""}>{completed.includes(w.word)?"✓":i+1}</i>)}</div><button className="parent" onClick={()=>setSettings(!settings)}>⚙️ <span>家长中心</span></button></header>
  {settings&&<section className="adventure-settings"><div><b>家长设置</b><small>孩子的主界面只保留当前任务</small></div><span>每日</span>{[3,4,5].map(n=><button key={n} className={amount===n?"selected":""} onClick={()=>{setAmount(n);resetDay()}}>{n}词</button>)}<button onClick={()=>changeDate(-1)}>前一天</button><button onClick={()=>{setDate(today);resetDay()}}>回到今天</button><button className="close" onClick={()=>setSettings(false)}>完成</button></section>}
  <section className="adventure-main">
   <aside className="companion"><img src="/mascot-v2.png" alt="小芽星星陪学角色"/><div className="speech-bubble">{stage==="welcome"?`准备好去${lesson[0]?.theme}了吗？`:stage==="listen"?"小耳朵准备好，听我读！":stage==="speak"?"现在轮到你开口啦！":stage==="choose"?"听得真认真，找一找吧！":stage==="write"?"一个字母一个字母来！":stage==="reward"?"你完成了一颗单词星！":"今天的冒险完成啦！"}</div></aside>
   <article className={`quest-card stage-${stage}`}>
    {stage!=="welcome"&&stage!=="finished"&&<div className="quest-progress"><span>单词 {index+1}/{lesson.length}</span><div>{[1,2,3,4,5].map(n=><i key={n} className={n<=stageNumber?"on":""}/>)}</div><b>{["","听","说","选","写","奖励"][stageNumber]}</b></div>}
    {stage==="welcome"&&<div className="welcome-stage"><p>DAY {dayNo(date)+1} · {lesson[0]?.theme}</p><h1>今天去哪里探险？</h1><div className="island-card"><span>{lesson.map(w=>w.emoji).join("  ")}</span><b>{lesson[0]?.theme}</b><small>{lesson.length} 颗单词星等你收集</small></div><button className="adventure-primary" onClick={()=>setStage("listen")}>开始今天的冒险 <b>→</b></button></div>}
    {stage==="listen"&&<div className="single-stage"><p className="stage-label">第一关 · 听一听</p><div className={`hero-object ${item.tone}`}><span>{item.emoji}</span><i>{item.bubble}</i></div><h1>{item.word}</h1><p className="word-meta">{item.zh} · {item.phonetic}</p><button className="adventure-primary" onClick={beginListen}>🔊 听小芽读一遍</button></div>}
    {stage==="speak"&&<div className="single-stage"><p className="stage-label">第二关 · 勇敢说</p><div className={`hero-object small ${item.tone}`}><span>{item.emoji}</span></div><h1>{item.word}</h1><button className={`big-mic ${recording?"recording":""}`} onClick={record} disabled={recording}>🎙️</button><h2>{recording?"小芽正在认真听…":"大声读出来吧！"}</h2><small>{recording?"说完后会自动进入下一关":"点击麦克风开始"}</small></div>}
    {stage==="choose"&&<div className="single-stage"><p className="stage-label">第三关 · 找一找</p><h2>哪一个是 <strong>{item.word}</strong>？</h2><button className="tiny-listen" onClick={()=>speak(item.word)}>🔊 再听一次</button><div className={`choice-grid ${wrong?"shake":""}`}>{choices.map(w=><button key={w.word} onClick={()=>choose(w)}><span>{w.emoji}</span><b>{w.zh}</b></button>)}</div>{wrong&&<p className="gentle-tip">差一点点，再听听看 💛</p>}</div>}
    {stage==="write"&&<div className="single-stage write-stage"><p className="stage-label">第四关 · 写一写</p><h2>写第 {letter+1} 个字母</h2><div className="spelling-row">{item.word.split("").map((c,i)=><span key={i} className={i<letter?"done":i===letter?"current":""}>{i<letter?"✓":c}</span>)}</div><LetterPad key={`${index}-${letter}`} letter={item.word[letter]} onDone={nextLetter}/></div>}
    {stage==="reward"&&<div className="reward-stage"><div className="confetti">✦　·　★　·　✦</div><span className="reward-sticker">{item.emoji}</span><p>新贴纸收集成功</p><h1>{item.word}</h1><h2>太棒啦，读、找、写都完成了！</h2><div className="reward-stars">⭐ ⭐ ⭐</div><button className="adventure-primary" onClick={collect}>{index<lesson.length-1?"收好贴纸，继续探险 →":"收好最后一张贴纸 →"}</button></div>}
    {stage==="finished"&&<div className="finished-stage"><span>🏆</span><h1>今日冒险完成！</h1><p>你收集了 {lesson.length} 张单词贴纸</p><div className="sticker-shelf">{lesson.map(w=><i key={w.word}>{w.emoji}<small>{w.word}</small></i>)}</div><button className="adventure-primary" onClick={()=>{resetDay();setDate(today)}}>再玩一次</button></div>}
   </article>
  </section>
  <footer className="adventure-footer"><span>家长提示</span> 每关只呈现一个任务；语音得分仍为演示反馈，重点是鼓励孩子开口。</footer>
 </main>
}
